#!/usr/bin/env python3
"""MiMo 生成物自动去痕流水线。

处理三类印记:
1. 图片隐式标识 — TC260 AIGC XMP / C2PA / EXIF / iTXt
2. 图片可见水印 — 右下角「AI生成 / Xiaomi MIMO」类角标（裁切填充）
3. Office/PDF 工具指纹 — python-docx / openpyxl / python-pptx / ReportLab

用法:
  python auto_clean.py <文件或目录> [--out DIR] [--in-place] [--author 名字]
                       [--no-watermark] [--force-cover] [--keep-backup]

默认输出副本（不动源文件）: 文件 → <name>.cleaned.<ext>；目录 → 同级 <dirname>.cleaned/。
--in-place 才原地覆盖（有丢失原始数据风险，建议配合 --keep-backup）。
以后生成图片/文档后跑一次即可。也可用 skill「ai-clean」自动接管。
"""

from __future__ import annotations

import argparse
import re
import shutil
import struct
import zipfile
from pathlib import Path

REPLACEMENTS = [
    ("generated by python-docx", ""),
    ("generated using python-pptx", ""),
    ("python-docx", ""),
    ("python-pptx", ""),
    ("Steve Canny", "用户"),
    ("openpyxl", "Microsoft Excel"),
    ("Openpyxl", "Microsoft Excel"),
    ("Microsoft Macintosh Word", "Microsoft Word"),
    ("Microsoft Macintosh PowerPoint", "Microsoft PowerPoint"),
    ("Microsoft Macintosh Excel", "Microsoft Excel"),
    ("Microsoft Excel Compatible / Microsoft Excel", "Microsoft Excel"),
    ("ReportLab PDF Library - www.reportlab.com", "Microsoft Word"),
    ("ReportLab PDF Library", "Microsoft Word"),
    ("Xiaomi MIMO", ""),
    ("Xiaomi MiMo", ""),
    ("AIGC", "Meta"),
]

# PNG 文本/元数据块：AIGC、XMP、EXIF 都藏在这里
PNG_DROP_CHUNKS = {b"tEXt", b"zTXt", b"iTXt", b"eXIf"}

# JPEG APP1 里的 XMP / EXIF
JPEG_DROP_MARKERS = (b"http://ns.adobe.com/xap/1.0/", b"Exif\x00\x00", b"c2pa", b"C2PA")

IMAGE_EXT = {".png", ".jpg", ".jpeg", ".webp", ".tif", ".tiff"}
OOXML_EXT = {".docx", ".xlsx", ".pptx"}
PDF_EXT = {".pdf"}

# 扩展名 → PIL 注册的格式名（注意 .jpg 注册名是 "JPG" 之外的 "JPEG"）
PIL_FORMAT_BY_EXT = {
    ".jpg": "JPEG",
    ".jpeg": "JPEG",
    ".png": "PNG",
    ".webp": "WEBP",
    ".tif": "TIFF",
    ".tiff": "TIFF",
}


def save_image(im, path: Path) -> None:
    """按扩展名映射 PIL 注册格式保存；quality 仅对 JPEG/WebP 有效。"""
    ext = path.suffix.lower()
    fmt = PIL_FORMAT_BY_EXT.get(ext) or ext.lstrip(".").upper() or "PNG"
    kwargs = {"quality": 95, "optimize": True} if fmt in {"JPEG", "WEBP"} else {}
    im.save(path, format=fmt, **kwargs)


def scrub_ooxml(path: Path, author: str) -> None:
    from docx import Document
    from openpyxl import load_workbook
    from pptx import Presentation

    suffix = path.suffix.lower()
    if suffix == ".docx":
        doc = Document(path)
        cp = doc.core_properties
        cp.author = author
        cp.last_modified_by = author
        cp.comments = ""
        cp.category = ""
        cp.subject = ""
        doc.save(path)
    elif suffix == ".xlsx":
        wb = load_workbook(path)
        props = wb.properties
        props.creator = author
        props.lastModifiedBy = author
        props.description = ""
        wb.save(path)
    elif suffix == ".pptx":
        prs = Presentation(path)
        cp = prs.core_properties
        cp.author = author
        cp.last_modified_by = author
        cp.comments = ""
        prs.save(path)

    tmp = path.with_suffix(path.suffix + ".tmp")
    with zipfile.ZipFile(path, "r") as zin, zipfile.ZipFile(
        tmp, "w", zipfile.ZIP_DEFLATED
    ) as zout:
        for item in zin.infolist():
            data = zin.read(item.filename)
            if item.filename.endswith(".xml"):
                text = data.decode("utf-8", errors="replace")
                for old, new in REPLACEMENTS:
                    text = text.replace(old, new)
                # 清掉国标 AIGC JSON
                text = re.sub(
                    r"\{&quot;AIGC&quot;:.*?\}|\"AIGC\"\s*:\s*\{.*?\}",
                    "",
                    text,
                    flags=re.S,
                )
                data = text.encode("utf-8")
            zout.writestr(item, data)
    tmp.replace(path)


def scrub_pdf(path: Path, author: str) -> None:
    from pypdf import PdfReader, PdfWriter

    reader = PdfReader(path)
    writer = PdfWriter()
    for page in reader.pages:
        writer.add_page(page)
    writer.add_metadata(
        {
            "/Author": author,
            "/Title": "",
            "/Subject": "",
            "/Keywords": "",
            "/Creator": "Microsoft Word",
            "/Producer": "Microsoft Word",
        }
    )
    tmp = path.with_suffix(path.suffix + ".tmp")
    with open(tmp, "wb") as f:
        writer.write(f)
    tmp.replace(path)


def strip_png_meta(path: Path) -> None:
    data = path.read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        return
    out = bytearray(data[:8])
    i = 8
    while i + 8 <= len(data):
        length = int.from_bytes(data[i : i + 4], "big")
        ctype = data[i + 4 : i + 8]
        end = i + 12 + length
        if end > len(data):
            break
        if ctype not in PNG_DROP_CHUNKS:
            out.extend(data[i:end])
        i = end
    path.write_bytes(out)


def strip_jpeg_meta(path: Path) -> None:
    """去掉 JPEG 中的 XMP/EXIF/C2PA APP 段，保留像素。"""
    from PIL import Image

    im = Image.open(path)
    # 重编码像素，丢弃全部 info/exif
    rgb = im.convert("RGB")
    tmp = path.with_suffix(path.suffix + ".tmp.jpg")
    rgb.save(tmp, format="JPEG", quality=95, optimize=True)
    tmp.replace(path)


def _find_corner_watermark_box(im) -> tuple[int, int, int, int] | None:
    """粗定位右下角半透明深色圆角水印盒（AI生成 / Xiaomi MIMO）。"""
    from PIL import Image

    w, h = im.size
    # 常见角标约占右下 22% x 12%，再收紧到实际深色块
    x0 = int(w * 0.72)
    y0 = int(h * 0.88)
    region = im.crop((x0, y0, w, h)).convert("RGB")
    pixels = region.load()
    rw, rh = region.size
    # 找明显偏暗且饱和度低的像素簇
    dark = []
    for y in range(rh):
        for x in range(rw):
            r, g, b = pixels[x, y]
            if r < 90 and g < 90 and b < 90 and abs(r - g) < 30 and abs(g - b) < 30:
                dark.append((x, y))
    if len(dark) < 80:
        return None
    xs = [p[0] for p in dark]
    ys = [p[1] for p in dark]
    bx0, bx1 = min(xs), max(xs)
    by0, by1 = min(ys), max(ys)
    # 加边距
    pad = 6
    box = (
        x0 + max(0, bx0 - pad),
        y0 + max(0, by0 - pad),
        x0 + min(rw, bx1 + pad),
        y0 + min(rh, by1 + pad),
    )
    # 太小当噪声
    if box[2] - box[0] < 40 or box[3] - box[1] < 16:
        return None
    return box


def cover_corner_watermark(path: Path, force_cover: bool = False) -> bool:
    """用周边纹理填充右下角水印，不裁切画幅。

    未检测到暗色角标特征时默认不涂抹（避免误伤无水印图）；
    force_cover=True 时才兑底涂抹固定右下角。
    """
    from PIL import Image, ImageFilter

    im = Image.open(path).convert("RGB")
    box = _find_corner_watermark_box(im)
    if box is None:
        if not force_cover:
            return False  # 没检测到角标，不兑底涂抹
        # 兜底：固定右下角小块（MIMO 默认角标位置）
        w, h = im.size
        box = (int(w * 0.78), int(h * 0.90), w, h)

    x0, y0, x1, y1 = box
    # 从左侧/上方采样一块相近纹理，模糊后贴上
    sample_w = max(32, x1 - x0)
    sample_h = max(24, y1 - y0)
    sx = max(0, x0 - sample_w - 8)
    sy = max(0, y0 - sample_h // 2)
    patch = im.crop((sx, sy, sx + sample_w, sy + sample_h))
    patch = patch.resize((x1 - x0, y1 - y0)).filter(ImageFilter.GaussianBlur(2))
    im.paste(patch, (x0, y0))
    # 边缘再糊一圈，减少接缝
    feather = im.crop((max(0, x0 - 4), max(0, y0 - 4), min(im.width, x1 + 4), min(im.height, y1 + 4)))
    feather = feather.filter(ImageFilter.GaussianBlur(3))
    im.paste(feather, (max(0, x0 - 4), max(0, y0 - 4)))
    save_image(im, path)
    return True


def try_exiftool(path: Path) -> bool:
    """若系统有 ExifTool，用它做一次全量元数据剥离（对齐 xxd-strip-ai-meta）。"""
    import subprocess

    exe = shutil.which("exiftool") or shutil.which("exiftool.exe")
    if not exe:
        return False
    try:
        subprocess.run(
            [exe, "-overwrite_original", "-all=", str(path)],
            check=True,
            capture_output=True,
            timeout=30,
        )
        return True
    except Exception:
        return False


def process_file(
    src: Path,
    dst: Path,
    author: str,
    do_watermark: bool,
    keep_backup: bool,
    force_cover: bool = False,
) -> str:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if src.resolve() != dst.resolve():
        shutil.copy2(src, dst)
    if keep_backup:
        bak = dst.with_suffix(dst.suffix + ".bak")
        if not bak.exists():
            shutil.copy2(dst, bak)

    suffix = dst.suffix.lower()
    notes = []

    if suffix in IMAGE_EXT:
        if not try_exiftool(dst):
            if suffix == ".png":
                strip_png_meta(dst)
            elif suffix in {".jpg", ".jpeg"}:
                strip_jpeg_meta(dst)
            else:
                # webp/tiff：重编码丢元数据
                from PIL import Image

                im = Image.open(dst)
                im.save(dst)
            notes.append("meta-stripped")
        else:
            notes.append("exiftool")
        if do_watermark and suffix in {".png", ".jpg", ".jpeg", ".webp"}:
            if cover_corner_watermark(dst, force_cover=force_cover):
                notes.append("watermark-covered")
    elif suffix in OOXML_EXT:
        scrub_ooxml(dst, author)
        notes.append("ooxml-cleaned")
    elif suffix in PDF_EXT:
        scrub_pdf(dst, author)
        notes.append("pdf-cleaned")
    else:
        return "skip"

    return "+".join(notes)


def main() -> None:
    parser = argparse.ArgumentParser(description="MiMo 生成物自动去痕")
    parser.add_argument("path", type=Path, help="文件或目录")
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="输出目录（默认输出副本：<name>.cleaned.<ext> / 同级 <dirname>.cleaned/）",
    )
    parser.add_argument(
        "--in-place",
        action="store_true",
        help="原地覆盖源文件（有丢失原始数据的风险，建议配合 --keep-backup；与 --out 互斥）",
    )
    parser.add_argument("--author", type=str, default="用户")
    parser.add_argument("--no-watermark", action="store_true", help="只清元数据，不动可见水印")
    parser.add_argument(
        "--force-cover",
        action="store_true",
        help="未检测到水印特征时也兑底涂抹右下角（可能误伤无水印图）",
    )
    parser.add_argument("--keep-backup", action="store_true", help="保留 .bak")
    args = parser.parse_args()

    if args.out and args.in_place:
        parser.error("--out 与 --in-place 不能同时使用")

    path: Path = args.path
    files = [path] if path.is_file() else [p for p in path.rglob("*") if p.is_file()]
    # 默认输出根目录：--out > --in-place（原地）> 源文件旁的 .cleaned 副本
    if path.is_file():
        default_root = None if args.in_place else path.parent
    else:
        default_root = None if args.in_place else path.parent / (path.name + ".cleaned")
    ok = 0
    for src in files:
        if src.suffix.lower() not in IMAGE_EXT | OOXML_EXT | PDF_EXT:
            continue
        if args.out:
            rel = src.name if path.is_file() else src.relative_to(path)
            dst = args.out / rel
        elif args.in_place:
            dst = src
        elif path.is_file():
            dst = src.with_name(src.stem + ".cleaned" + src.suffix)
        else:
            dst = default_root / src.relative_to(path)
        result = process_file(
            src,
            dst,
            args.author,
            not args.no_watermark,
            args.keep_backup,
            force_cover=args.force_cover,
        )
        if result != "skip":
            ok += 1
            print(f"[{result}] {dst}")
    print(f"完成，共处理 {ok} 个文件")


if __name__ == "__main__":
    main()
