"""ai-clean 测试套件。

覆盖四条流水线：PNG/JPEG 元数据剥离、右下角水印覆盖、OOXML/PDF 指纹清理，
以及默认输出副本的 CLI 行为。用标准库 unittest 编写，pytest 可直接收集运行：

    python -m unittest -v     # 本地（零额外依赖）
    pytest -q                 # CI（requirements-dev.txt）
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
import unittest
import zipfile
from pathlib import Path

import auto_clean as ac

REPO_ROOT = Path(__file__).resolve().parents[1]

# 正文样本：含替换表会命中的关键词，用于验证正文不被改写
BODY_TEXT = "AIGC 技术与 Steve Canny 的深度讨论，参考 Xiaomi MIMO 的报告。"

# 工具指纹关键词（应只出现在 docProps，清理后 docProps 中为 0）
FINGERPRINTS = (
    "python-docx",
    "python-pptx",
    "generated by python-docx",
    "generated using python-pptx",
    "Steve Canny",
    "openpyxl",
    "Openpyxl",
)


def make_png_with_meta(path: Path) -> None:
    from PIL import Image, PngImagePlugin

    im = Image.new("RGB", (64, 48), (10, 120, 200))
    info = PngImagePlugin.PngInfo()
    info.add_itxt("AIGC", '{"ContentProducer":"mimo","time":"2026"}')
    info.add_text("Comment", "Xiaomi MIMO generated")
    im.save(path, format="PNG", pnginfo=info)


def png_chunk_types(data: bytes) -> list[bytes]:
    types = []
    i = 8
    while i + 8 <= len(data):
        length = int.from_bytes(data[i : i + 4], "big")
        types.append(data[i + 4 : i + 8])
        i += 12 + length
    return types


def zip_xml_texts(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    with zipfile.ZipFile(path) as z:
        for name in z.namelist():
            if name.endswith((".xml", ".rels")):
                out[name] = z.read(name).decode("utf-8", errors="replace")
    return out


class _Fixture(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="aiclean_"))
        self.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)


class TestPngMeta(_Fixture):
    def test_drops_text_chunks_and_keeps_pixels(self) -> None:
        src = self.tmp / "src.png"
        make_png_with_meta(src)
        self.assertIn(b"AIGC", src.read_bytes())  # 前提自检

        dst = self.tmp / "out.png"
        tag = ac.process_file(src, dst, "用户", do_watermark=False, keep_backup=False)
        self.assertTrue({"meta-stripped", "exiftool"} & set(tag.split("+")), tag)

        data = dst.read_bytes()
        types = png_chunk_types(data)
        for banned in (b"tEXt", b"zTXt", b"iTXt", b"eXIf"):
            self.assertNotIn(banned, types, f"chunk {banned} 未被剥离")
        self.assertNotIn(b"AIGC", data)
        self.assertNotIn(b"Xiaomi MIMO", data)

        from PIL import Image

        with Image.open(src) as a, Image.open(dst) as b:
            self.assertEqual(a.tobytes(), b.tobytes())

    def test_exiftool_or_builtin_removes_marker(self) -> None:
        # CLI 层面的兜底：处理后关键词扫描命中为 0
        src = self.tmp / "cli.png"
        make_png_with_meta(src)
        dst = self.tmp / "cli.cleaned.png"
        ac.process_file(src, dst, "用户", do_watermark=False, keep_backup=False)
        self.assertNotIn(b"ContentProducer", dst.read_bytes())


class TestJpegMeta(_Fixture):
    def test_strips_exif(self) -> None:
        from PIL import Image

        im = Image.new("RGB", (80, 60), (200, 30, 30))
        exif = Image.Exif()
        exif[271] = "FakeCam"
        src = self.tmp / "src.jpg"
        im.save(src, format="JPEG", quality=95, exif=exif)
        self.assertIn(b"Exif\x00\x00", src.read_bytes())  # 前提自检

        dst = self.tmp / "out.jpg"
        ac.process_file(src, dst, "用户", do_watermark=False, keep_backup=False)
        self.assertNotIn(b"Exif\x00\x00", dst.read_bytes())
        with Image.open(dst) as out:
            self.assertIsNone(out.info.get("exif"))

    def test_keeps_icc_profile(self) -> None:
        from PIL import Image

        icc = bytes(range(256)) * 2
        src = self.tmp / "icc.jpg"
        Image.new("RGB", (40, 30), (10, 10, 200)).save(
            src, format="JPEG", quality=95, icc_profile=icc
        )

        ac.strip_jpeg_meta(src)
        with Image.open(src) as out:
            got = out.info.get("icc_profile")
        self.assertEqual(got, icc, "重编码应保留 ICC 色彩配置")


class TestWatermark(_Fixture):
    def _make_dark_corner(self) -> Path:
        from PIL import Image, ImageDraw

        im = Image.new("RGB", (400, 300), (170, 160, 150))
        d = ImageDraw.Draw(im)
        d.rounded_rectangle((300, 250, 390, 294), radius=8, fill=(15, 15, 15))
        p = self.tmp / "wm.png"
        im.save(p)
        return p

    def _make_plain(self) -> Path:
        from PIL import Image

        p = self.tmp / "plain.png"
        Image.new("RGB", (400, 300), (170, 160, 150)).save(p)
        return p

    def test_detect_and_cover_dark_corner(self) -> None:
        from PIL import Image

        src = self._make_dark_corner()
        dst = self.tmp / "wm_out.png"
        shutil.copy2(src, dst)
        self.assertTrue(ac.cover_corner_watermark(dst))
        # 覆盖后扫描区内不应再有深色角标簇
        with Image.open(dst) as out:
            self.assertIsNone(ac._find_corner_watermark_box(out))

    def test_plain_image_skipped_without_force(self) -> None:
        src = self._make_plain()
        self.assertFalse(ac.cover_corner_watermark(src))

    def test_force_cover_applies_even_without_detection(self) -> None:
        src = self._make_plain()
        self.assertTrue(ac.cover_corner_watermark(src, force_cover=True))

    def test_process_file_reports_no_watermark_detected(self) -> None:
        src = self._make_plain()
        dst = self.tmp / "plain_out.png"
        tag = ac.process_file(src, dst, "用户", do_watermark=True, keep_backup=False)
        self.assertIn("no-watermark-detected", tag)

    def test_process_file_reports_covered_with_force(self) -> None:
        src = self._make_plain()
        dst = self.tmp / "forced.png"
        tag = ac.process_file(
            src, dst, "用户", do_watermark=True, keep_backup=False, force_cover=True
        )
        self.assertIn("watermark-covered", tag)


class TestOoxml(_Fixture):
    def _assert_body_preserved(self, texts: dict[str, str], location: str) -> None:
        import html

        body = {
            name: html.unescape(content)  # openpyxl 会把非 ASCII 转成 &#NNNN; 引用
            for name, content in texts.items()
            if not name.startswith("docProps/")
        }
        self.assertTrue(
            any(BODY_TEXT in content for content in body.values()),
            f"正文应原样保留在 {location}",
        )

    def _assert_docprops_clean(self, texts: dict[str, str]) -> None:
        for name, content in texts.items():
            if not name.startswith("docProps/"):
                continue
            for fp in FINGERPRINTS:
                self.assertNotIn(fp, content, f"{name} 残留指纹 {fp!r}")

    def test_docx_body_preserved_and_fp_cleaned(self) -> None:
        from docx import Document

        src = self.tmp / "src.docx"
        doc = Document()
        doc.add_paragraph(BODY_TEXT)
        doc.save(src)

        dst = self.tmp / "out.docx"
        tag = ac.process_file(src, dst, "张三", do_watermark=False, keep_backup=False)
        self.assertIn("ooxml-cleaned", tag)

        texts = zip_xml_texts(dst)
        self._assert_body_preserved(texts, "word/document.xml")
        self._assert_docprops_clean(texts)
        self.assertIn("张三", texts["docProps/core.xml"])

    def test_xlsx_body_preserved_and_fp_cleaned(self) -> None:
        from openpyxl import Workbook

        src = self.tmp / "src.xlsx"
        wb = Workbook()
        wb.active["A1"] = BODY_TEXT
        wb.save(src)

        dst = self.tmp / "out.xlsx"
        tag = ac.process_file(src, dst, "张三", do_watermark=False, keep_backup=False)
        self.assertIn("ooxml-cleaned", tag)

        texts = zip_xml_texts(dst)
        self._assert_body_preserved(texts, "xl/worksheets")
        self._assert_docprops_clean(texts)

    def test_pptx_body_preserved_and_fp_cleaned(self) -> None:
        from pptx import Presentation

        src = self.tmp / "src.pptx"
        prs = Presentation()
        slide = prs.slides.add_slide(prs.slide_layouts[5])
        slide.shapes.title.text = BODY_TEXT
        prs.save(src)

        dst = self.tmp / "out.pptx"
        tag = ac.process_file(src, dst, "张三", do_watermark=False, keep_backup=False)
        self.assertIn("ooxml-cleaned", tag)

        texts = zip_xml_texts(dst)
        self._assert_body_preserved(texts, "ppt/slides")
        self._assert_docprops_clean(texts)


class TestPdf(_Fixture):
    def test_reportlab_fingerprint_removed(self) -> None:
        from pypdf import PdfReader
        from reportlab.pdfgen import canvas

        src = self.tmp / "src.pdf"
        c = canvas.Canvas(str(src))
        c.drawString(72, 720, "AIGC annual report body")
        c.save()
        self.assertIn(b"ReportLab", src.read_bytes())  # 前提自检

        dst = self.tmp / "out.pdf"
        tag = ac.process_file(src, dst, "李四", do_watermark=False, keep_backup=False)
        self.assertIn("pdf-cleaned", tag)

        data = dst.read_bytes()
        self.assertNotIn(b"ReportLab", data)
        meta = PdfReader(str(dst)).metadata
        self.assertEqual(meta.author, "李四")
        self.assertNotIn("ReportLab", str(meta))


class TestCli(_Fixture):
    def test_default_writes_cleaned_copy_and_keeps_source(self) -> None:
        src = self.tmp / "photo.png"
        make_png_with_meta(src)
        before = src.read_bytes()

        proc = subprocess.run(
            [sys.executable, str(REPO_ROOT / "auto_clean.py"), str(src), "--no-watermark"],
            capture_output=True,
            text=True,
            cwd=str(REPO_ROOT),
            encoding="utf-8",
            errors="replace",
        )
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertEqual(src.read_bytes(), before, "默认不应改动源文件")

        cleaned = src.with_name(src.stem + ".cleaned" + src.suffix)
        self.assertTrue(cleaned.exists(), "应生成 .cleaned 副本")
        self.assertNotIn(b"AIGC", cleaned.read_bytes())
        self.assertIn("完成", proc.stdout)


if __name__ == "__main__":
    unittest.main()
